packages:
  - docs
  - examples/*
  - spikes/**
  - packages/*
allowBuilds:
  esbuild: false
  sharp: false
linkWorkspacePackages: true
preferWorkspacePackages: true
# This prevents the examples to have the `workspace:` prefix
saveWorkspaceProtocol: false
